<center><h1> Corréction Série de Travaux Pratiques N° 6 - Machine Learning </h1></center>
<center><h2> Regression Logistique</h2></center>

---



# **Partie I : Regression Logistique**

Vous trouverez ci-joint un exemple d'utilisation d'algorithme de regréssion logistique avec les quatres étapes principales.

In [22]:
# Étape 1 : Importer les packages et fonctions
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Étape 2 : Obtenir les données
# Créer un ensemble de données simple avec les caractéristiques 'x' et la cible 'y'
x = np.arange(10).reshape(-1, 1)  
y = np.array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])  # Cible : étiquettes binaires

# Étape 3 : Créer un modèle et l'entraîner
# Instancier le modèle de régression logistique avec des paramètres spécifiés
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0, max_iter=100)
# Ajuster le modèle aux données
model.fit(x, y)

# Étape 4 : Évaluer le modèle
# Prédire les probabilités des classes pour les données d'entrée
p_pred = model.predict_proba(x)
# Prédire les étiquettes de classe pour les données d'entrée
y_pred = model.predict(x)
# Calculer l'exactitude du modèle
score_ = model.score(x, y)
# Calculer la matrice de confusion pour évaluer les performances du modèle
conf_m = confusion_matrix(y, y_pred)
print(conf_m)
# Générer un rapport de classification détaillé
report = classification_report(y, y_pred)
print(report)


[[2 1]
 [1 6]]
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



In [23]:
from sklearn.metrics import confusion_matrix

# Exemple d'étiquettes réelles et prédites
y_true = [2, 0, 2, 2, 0, 1]  # Étiquettes réelles
y_pred = [0, 0, 2, 2, 0, 2]  # Étiquettes prédites

# Calcul de la matrice de confusion
# La matrice de confusion compare les étiquettes réelles aux étiquettes prédites
matrix = confusion_matrix(y_true, y_pred)

# Affichage de la matrice de confusion
print(matrix)


[[2 0 0]
 [0 0 1]
 [1 0 2]]


In [24]:
# Afficher les données, les paramètres du modèle et les résultats de l'évaluation
print('x:', x)  # Afficher les caractéristiques
print('y:', y)  # Afficher les étiquettes

print('intercept:', model.intercept_)   # Afficher l'intercept du modèle
print('coef:', model.coef_)             # Afficher les coefficients des caractéristiques
print('p_pred:', p_pred)                # Afficher les probabilités prédites pour chaque classe
print('y_pred:', y_pred)                # Afficher les étiquettes prédites
print('score_:', score_)                # Afficher l'exactitude du modèle
print('conf_m:', conf_m)                # Afficher la matrice de confusion
print('report:', report)                # Afficher le rapport de classification

x: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y: [0 1 0 0 1 1 1 1 1 1]
intercept: [-1.51632619]
coef: [[0.703457]]
p_pred: [[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]
y_pred: [0, 0, 2, 2, 0, 2]
score_: 0.8
conf_m: [[2 1]
 [1 6]]
report:               precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



# **Partie II : Classification Binaire**

L'objectif de l'ensemble de données "**diabetes.csv**" est de prédire, sur la base de mesures diagnostiques, si un patient **souffre de diabète ou pas**.

Ce dataset contient les caractéristiques suivants

**Grossesses**: Nombre de fois enceintes.

**Glucose**: concentration plasmatique de glucose à 2 heures lors d'un test oral de tolérance au glucose.

**Pression artérielle** : tension artérielle diastolique (mm Hg).

**Épaisseur de la peau** : épaisseur du pli cutané du triceps (mm).

**Insuline** : insuline sérique de 2 heures (mu U/ml).

**IMC** : Indice de masse corporelle (poids en kg/(taille en m)^2).

**DiabetesPedigreeFunction** : fonction généalogique du diabète.

**Âge** : Âge (ans).

**Résultat** : variable de classe (0 ou 1).

### **Questions :**

Étape 1 : Importer et afficher et explorer l'ensemble de données "**diabetes.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [25]:
# 1: Importer les bibliothèques et afficher/explorer l'ensemble de données
import pandas as pd  
import matplotlib.pyplot as plt

# Importer l'ensemble de données depuis un fichier CSV
data = pd.read_csv("diabetes.csv")

# Afficher les premières lignes de l'ensemble de données pour un aperçu rapide
print(data.head())


   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [26]:
# 2 : Définir X et y 
# X est constitué de toutes les colonnes sauf 'Outcome'
X = data.drop(columns='Outcome')
# y est la colonne 'Outcome' qui contient la variable dépendante
y = data['Outcome']

In [27]:
# Afficher les types de données de X pour vérifier
print(X.dtypes)

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
dtype: object


In [28]:
from sklearn.model_selection import train_test_split
# 4 : Diviser les données en ensembles d'entraînement et de test
# Utiliser la fonction train_test_split pour diviser les données
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Afficher les dimensions des ensembles d'entraînement et de test pour vérifier
print("Dimensions de l'ensemble d'entraînement X :", X_train.shape)
print("Dimensions de l'ensemble de test X :", X_test.shape)
print("Dimensions de l'ensemble d'entraînement Y :", Y_train.shape)
print("Dimensions de l'ensemble de test Y :", Y_test.shape)

Dimensions de l'ensemble d'entraînement X : (614, 8)
Dimensions de l'ensemble de test X : (154, 8)
Dimensions de l'ensemble d'entraînement Y : (614,)
Dimensions de l'ensemble de test Y : (154,)


In [29]:
# 5 : Définir l'algorithme de régression logistique
from sklearn.linear_model import LogisticRegression
# Définir le modèle de régression logistique
model  = LogisticRegression()

# Entraîner le modèle
model .fit(X_train, Y_train)


c:\Users\Maryam\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [30]:
# 6 : Tester les données de test en utilisant votre modèle
# Prédire les valeurs pour l'ensemble de test
Y_pred = model.predict(X_test)
print("Prédictions :", Y_pred)
from sklearn.metrics import confusion_matrix
# Afficher la matrice de confusion pour évaluer les performances du modèle
print("\nMatrice de confusion :")
print(confusion_matrix(Y_test, Y_pred))


Prédictions : [0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 1 1 1 1 1 1 1
 0 1 1 0 1 1 0 0 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 1 1 0 0 0
 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0
 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0]

Matrice de confusion :
[[78 21]
 [18 37]]


In [31]:
#7 : Évaluation du modèle
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculer l'accuracy du modèle
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy du modèle :", accuracy)

# Afficher la matrice de confusion
conf_matrix = confusion_matrix(Y_test, Y_pred)
print("Matrice de confusion :\n", conf_matrix)

# Afficher le rapport de classification
class_report = classification_report(Y_test, Y_pred)
print("Rapport de classification :\n", class_report)


Accuracy du modèle : 0.7467532467532467
Matrice de confusion :
 [[78 21]
 [18 37]]
Rapport de classification :
               precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



In [32]:
#8 : Prédire avec de nouvelles valeurs
# Par exemple, prédire avec une nouvelle observation
new_data = [[1, 89, 66, 23, 94, 28.1, 0.167, 111]]  # Remplacer par vos nouvelles valeurs
new_prediction = model.predict(new_data)
print("Prédiction pour les nouvelles valeurs :", new_prediction)

Prédiction pour les nouvelles valeurs : [1]


c:\Users\Maryam\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


# **Partie II : Classification Multi-Classe**

Pour cette partie, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

### **Questions :**

Étape 1 : Importer, afficher et explorer l'ensemble de données "**iris.csv**"

Étape 2 : Créer dépendante d'une variable indépendante et stockée sur les variables X et Y.

Étape 3 : Transformer les chaînes en entier.

Étape 4 : Divisez les données en ensembles d'entrainement et de test.

Étape 5 : Définir l'algorithme de régression logistique.

Étape 6 :Tester les données de test en utilisant votre modèle.

Étape 7 : Évaluation du modèle.

Étape 8 : Prédire avec de nouvelles valeurs.

In [33]:
# 1: Importer les bibliothèques et afficher/explorer l'ensemble de données
import pandas as pd

# Importer l'ensemble de données
df = pd.read_csv('iris.csv')

# Afficher les premières lignes de l'ensemble de données
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [34]:
#2 : Créer la variable indépendante et dépendante, stockée sur les variables X et y
# Définir X et y :
X = df.drop(columns='variety')
y = df['variety']

In [35]:
#3 : Transformer les chaînes en entier
from sklearn.preprocessing import LabelEncoder

# Transformer les chaînes en entiers pour la variable dépendante
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
#4 : Diviser les données en ensembles d'entraînement et de test
from sklearn.model_selection import train_test_split

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [37]:
#5 : Définir l'algorithme de régression logistique
from sklearn.linear_model import LogisticRegression

# Définir le modèle de régression logistique
model = LogisticRegression(max_iter=1000, random_state=42)

# Entraîner le modèle
model.fit(X_train, y_train)


LogisticRegression(max_iter=1000, random_state=42)

In [38]:
#6 : Tester les données de test en utilisant votre modèle
# Faire des prédictions sur l'ensemble de test
y_pred = model.predict(X_test)

In [39]:
#7 : Evaluation du modèle
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculer l'accuracy du modèle
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy du modèle :", accuracy)

# Afficher la matrice de confusion
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matrice de confusion :\n", conf_matrix)

# Afficher le rapport de classification
class_report = classification_report(y_test, y_pred)
print("Rapport de classification :\n", class_report)


Accuracy du modèle : 1.0
Matrice de confusion :
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Rapport de classification :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [40]:
#8 : Prédire avec de nouvelles valeurs.
new_data = [[6.3,3.4,5.6,2.4]]  # Remplacer par vos nouvelles valeurs
new_prediction = model.predict(new_data)
new_species = label_encoder.inverse_transform(new_prediction)
print("Prédiction pour les nouvelles valeurs :", new_species)


Prédiction pour les nouvelles valeurs : ['Virginica']


c:\Users\Maryam\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
